const mockData = [
  {
    postID: "1",
    nickname: "가나다라",
    region: "서울",
    title: "충청도 같이 여행가실 분 구합니다~!~!",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "2",
    nickname: "가나다라",
    region: "충청도",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "3",
    nickname: "가나다라",
    region: "전라도",
    status: true,
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "4",
    nickname: "가나다라",
    region: "경기도",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "5",
    nickname: "가나다라",
    region: "제주도",
    status: true,
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "6",
    nickname: "가나다라",
    region: "기타",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "7",
    nickname: "가나다라",
    status: true,
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "8",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "9",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "10",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
];

export default mockData;
