const matchMockData = [
  {
    postID: "1",
    nickname: "가나다라",
    region: "서울",
    title: "충청도 같이 여행가실 분 구합니다~!~!",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "2",
    nickname: "가나다라",
    region: "충청도",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "3",
    nickname: "가나다라",
    region: "전라도",
    status: true,
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "4",
    nickname: "가나다라",
    region: "경기도",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "5",
    nickname: "가나다라",
    region: "제주도",
    status: true,
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "6",
    nickname: "가나다라",
    region: "기타",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "7",
    nickname: "가나다라",
    status: true,
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "8",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "9",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
  {
    postID: "10",
    status: true,
    nickname: "가나다라",
    region: "서울",
    title: "제목입니다",
    like: true,
    thumbnailImg: "https://picsum.photos/600/900",
  },
];

const freeMockData = [
  {
    communityId: "1",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "2",
    author: {
      email: "111@naver.com",
      nickname: "두자",
      profileImg: "",
    },
    region: "충청도",
    category: "맛집",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "3",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "4",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "5",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "경기도",
    category: "관광",
    title: "임진각 추천 볼거리 리스트 top100 주저리주저리",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "6",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "7",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "8",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "9",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "10",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
];

export { matchMockData, freeMockData };
