const matchMockData = [
  {
    postId: "1",
    author: {
      email: "jo522@naver.com",
      nickname: "쥰",
      profileImg:
        "https://res.cloudinary.com/dk9scwone/image/upload/v1671965264/default-user_j23wek.png",
    },
    region: "서울",
    title: "충청도 같이 여행가실 분 구합니다~!~!",
    userCount: 1,
    hopeGender: "30대",
    hopeAge: "여",
    content: "내용",
    status: true,
    duration: ["2022-12-24", "2023-01-18"],
    thumbnail: "https://picsum.photos/600/900",
    contact: "010-0000-0000",
  },
  {
    postId: "2",
    author: {
      email: "jo522@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg:
        "https://res.cloudinary.com/dk9scwone/image/upload/v1671965264/default-user_j23wek.png",
    },
    region: "충청도",
    title: "충청도 같이 여행가실 분 구합니다~!~!",
    userCount: 1,
    hopeGender: "30대",
    hopeAge: "여",
    content: "내용",
    status: true,
    duration: ["2022-12-24", "2023-01-18"],
    thumbnail: "https://picsum.photos/600/900",
    contact: "010-0000-0000",
  },
  {
    postId: "3",
    author: {
      email: "jo522@naver.com",
      nickname: "졸림",
      profileImg:
        "https://res.cloudinary.com/dk9scwone/image/upload/v1671965264/default-user_j23wek.png",
    },
    region: "경기도",
    title: "충청도 같이 여행가실 분 구합니다~!~!",
    userCount: 1,
    hopeGender: "30대",
    hopeAge: "여",
    content: "내용",
    status: true,
    duration: ["2022-12-24", "2023-01-18"],
    thumbnail: "https://picsum.photos/600/900",
    contact: "010-0000-0000",
  },
  {
    postId: "4",
    author: {
      email: "jo522@naver.com",
      nickname: "잠이솔솔솔",
      profileImg:
        "https://res.cloudinary.com/dk9scwone/image/upload/v1671965264/default-user_j23wek.png",
    },
    region: "서울",
    title: "여행메이트 구함",
    userCount: 1,
    hopeGender: "30대",
    hopeAge: "여",
    content: "내용",
    status: true,
    duration: ["2022-12-24", "2023-01-18"],
    thumbnail: "https://picsum.photos/600/900",
    contact: "010-0000-0000",
  },
  {
    postId: "5",
    author: {
      email: "jo522@naver.com",
      nickname: "쥰",
      profileImg:
        "https://res.cloudinary.com/dk9scwone/image/upload/v1671965264/default-user_j23wek.png",
    },
    region: "서울",
    title:
      "전라 순회 여행 22.12.24~23.01.18 여성 동행 세분 구합니다 문자주세요.",
    userCount: 1,
    hopeGender: "30대",
    hopeAge: "여",
    content: "내용",
    status: true,
    duration: ["2022-12-24", "2023-01-18"],
    thumbnail: "https://picsum.photos/600/900",
    contact: "010-0000-0000",
  },
];

const freeMockData = [
  {
    communityId: "1",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "2",
    author: {
      email: "111@naver.com",
      nickname: "두자",
      profileImg: "",
    },
    region: "충청도",
    category: "맛집",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "3",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "4",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "5",
    author: {
      email: "111@naver.com",
      nickname: "닉네임",
      profileImg: "",
    },
    region: "경기도",
    category: "관광",
    title: "임진각 추천 볼거리 리스트 top100 주저리주저리",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "6",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "7",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "8",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "9",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
  {
    communityId: "10",
    author: {
      email: "111@naver.com",
      nickname: "닉네임은여덟글자",
      profileImg: "",
    },
    region: "강원도",
    category: "숙박",
    title: "충청도 어디어디에 구경할만한 곳 있나요?",
    createdAt: "2022-11-04T04:57:01.267Z",
    content: "댓글 내용은 다음과 같다.",
  },
];

export { matchMockData, freeMockData };
